### PR TITLE
chore(projectstructure): setup project folder structure and clean code

### PR DESCRIPTION
**Pull request by Sagastein**
## setup project folder structure and clean code
- improving folder structure
- advanced routing and layout
- proper organization for folders and files
- clean and readable code base

### CODE REVIEW

**Review by tuyishimehope — APPROVED** [review]
LGTM

**Review by martinemahirwe — APPROVED** [review]
LGTM

**Review by Oliviier-dev — APPROVED** [review]
LGTM

**Review by Ke-bean — APPROVED** [review]
LGTM

**Review by SergeInGithub — APPROVED** [review]
Good work

**Pull request merged**
