### PR TITLE
ft(deleteCartProduct,ProductRow): user clear or update product quantity in their cart

### PR DESCRIPTION
**Pull request by martinemahirwe**
## ℹ️ Description

created the component for deleting single item functionality added functionality.
implemented the functionality for updating cart product
wrote tests for testing the functionality for clearing cart [delivers #187364826]

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

button for updating quantity
Screenshot from 2024-07-19 16-27-42
delete item from cart
Screenshot from 2024-07-19 16-27-32

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Ke-bean — COMMENTED** [review]
Please rebase and solve conflicts

**Review by Oliviier-dev — APPROVED** [review]
LGTM

**Review by Aldot-02 — APPROVED** [review]
LGTM

**Review by Ke-bean — APPROVED** [review]
LGTM

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Pull request merged**
