### PR TITLE
ft(orders)users can track their order status [#187364834]

### PR DESCRIPTION
**Pull request by shebz2023**
187364834

## ℹ️ Description

Users can view their Orders ,their order 's history ,when they press one of them they can see its details.In addition,when something gets wrong ...there is a giant button at the top for navigating to customer-center for help

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

Screenshot 2024-07-18 154835

Screenshot 2024-07-19 002409

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Sagastein — COMMENTED** [review]
Great work.
you can try to improve the design on order details page

**Review by Oliviier-dev — DISMISSED** [review]
LGTM

**Review by Sagastein — DISMISSED** [review]
Looks Great 🆗

**Review by SergeInGithub — DISMISSED** [review]
LGTM. just rebase and you're good to go! @shebz2023

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Pull request merged**
