### PR TITLE
fx(google-auth): getting authenticated user by extracting the token and encoded user from re-directed urls

### PR DESCRIPTION
**Pull request by Aldot-02**
## ℹ️ Description

As the backend will re-direct the users to different pages after verifying them, after the failure to get cookies at the re-directed pages, this will extract the token as well as the user from the url and clear them to avoid exposing them, while also setting them in the local storage and update the state to get authenticated user and his credentials.

## 🧪 How can this be tested?

This will be tested using the google button at the frontend.

## 📸 Screenshots

Screenshot 2024-07-03 at 11 02 59
Screenshot 2024-07-03 at 11 02 27
Screenshot 2024-07-03 at 11 02 00

## 📍 Type of change

Please check the options that are relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Sagastein — APPROVED** [review]
LGTM 🆗

**Review by martinemahirwe — APPROVED** [review]
LGTM

**Review by shebz2023 — APPROVED** [review]
LGTM

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Pull request merged**
